# K-Nearest Neighbor (KNN)

K-Nearest Neighbor is a supervised, non-parametric, lazy machine learning algorithm that can be used for both `classification` and `regression`. 

* It is a non-parametric algorithm as it does not make any assumptions about the data distribution.
* It is a lazy algorithm as model is computed during classification and is dependent on the test set.

KNN algorithm is based on feature similarity meaning, the classification is carried out by finding the similarity metric (usually distance) between the data points. It uses k 'nearest' points for performing classification

## How Does it Work?

The K-NN algorithm is quite simple. We just need following things to build a KNN model.
1. Dataset with label data
2. Distance Metric
3. Value of k

### Distance Metric

The KNN algorithm is based on similarity which is calculated using distance between two points. We will discuss some of the popular ones.
1. Euclidean Distance: This is one of the famous one from `coordinate geometry`. It is the common formula to calculate distance between two points. 
\begin{align}
distance=\sqrt{\sum_{i=1}^k(x_{i}-y_{i})^2} \\
\end{align}
2. Manhattan Distance: This one takes the absolute value of difference between the points rather than square root like Euclidean distance.
\begin{align}
distance=\sum_{i=1}^k|(x_{i}-y_{i})| \\
\end{align}

To classify an unknown datapoint followings steps are taken
1. Compute distance to each datapoint
2. Identify k nearest neighbors
3. Use class labels of nearest neighbors to determine the class label of unknown record by taking the majority vote.

To understand this better let us suppose that we have two classes denoted in the figure below by `-` (minus) and `+` (plus) sign. If we need to classify new data point `X` then first of all we need to select k. For this example we have taken k=3. Now, 3 nearest point to `X` is selected. Among these three points 2 are in class plus and one is in minus. If we take majority vote of classes then the new point is classified as plus.

![KNN Example](images/knn.png)

## Some Important Parameters

The following are some important parameters while building KNN models using scikit learn

1. n_neighborsint, default=5: This is the number of k that were discussing earlier.
2. metric: This parameter defines the distance metric that we have to use.

## Worked Out Example

We will build one classifier and one regressor using the KNN algorithm.

### Classification Using KNN

In [3]:
import warnings
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
import numpy as np
warnings.filterwarnings('ignore')

Load the Dataset

In [4]:
df = pd.read_csv("data/mushrooms.csv")

In [5]:
df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

Check the Dataset and the Distribution of Target

In [6]:
print("The total Number of Observations: {}".format(df.shape[0]))
print("Total Number of Edible Mushroom in the data set: {}".format(df['class'].value_counts()[0]))
print("Total Number of Poisonous Mushroom in the data set: {}".format(df['class'].value_counts()[1]))

The total Number of Observations: 8124
Total Number of Edible Mushroom in the data set: 4208
Total Number of Poisonous Mushroom in the data set: 3916

Separate features (X) and target (y) from the data

In [7]:
X = df.drop(columns=['class'],axis=1)
y = df['class']

Since all the features are categorical we need to convert them to numeric. One of the way is to create dummy variable. For example if we have the following dataset

| Feature1 | Feature1 | Feature3 |
|----------|----------|----------|
| a        | 1        | 2        |
| b        | 2        | 4        |
| a        | 5        | 9        |
| c        | 10       | 5        |

where Feature1 is categorical feature with values `a` , `b` and `c`. Then the feature1 is broken down into three features `feature1_a`,`feature1_b` and `feature1_c`. The value of each feature is either 1 or 0. If the value occurs in that row then respective feature 1 else 0. The dummy variables of this feature will be generated as 

| Feature1_a | Feature1_b | Feature1_c |
|------------|------------|------------|
| 1          | 0          | 0          |
| 0          | 1          | 0          |
| 1          | 0          | 0          |
| 0          | 0          | 1          |

In [8]:
X_dummy = pd.get_dummies(X, prefix=X.columns, drop_first=True)

In [9]:
X_dummy.head()

,cap-shape_c,cap-shape_f,cap-shape_k,cap-shape_s,cap-shape_x,cap-surface_g,cap-surface_s,cap-surface_y,cap-color_c,cap-color_e,...,population_n,population_s,population_v,population_y,habitat_g,habitat_l,habitat_m,habitat_p,habitat_u,habitat_w
0,0,0,0,0,1,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
1,0,0,0,0,1,0,1,0,0,0,...,1,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,1,0,0,0
3,0,0,0,0,1,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,0
4,0,0,0,0,1,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0

Set poisonous=0 and Edible=1

In [10]:
y = y.map({'p':0,'e':1}).values

Splitting Data into Training and Testing Set

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X_dummy,y,test_size=0.3,random_state=0)

Building the Model

In [12]:
clf = KNeighborsClassifier(n_neighbors=3)

Training the Model

In [13]:
clf.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

Making the Prediction

In [14]:
y_pred = clf.predict(X_test)

Calculate the Accuracy Score

In [15]:
print("The Accuracy of the Model is {:3f}".format(metrics.accuracy_score(y_test,y_pred)))

The Accuracy of the Model is 1.000000

## How to select the Best Value of K (n_neighbors) ?

We can use grid search technique to find the best value of k. We will build and see the accuracy score for each value of k from 1 to 25

In [16]:
from sklearn.model_selection import GridSearchCV
K_values=[i for i in range(26)]
parameters = {"n_neighbors":K_values}
mode=GridSearchCV(clf, parameters,scoring='accuracy',verbose=1,refit=True,cv=5,n_jobs=-1)

In [17]:
mode.fit(X_train,y_train)

Fitting 5 folds for each of 26 candidates, totalling 130 fits

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=3), n_jobs=-1,
             param_grid={'n_neighbors': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
                                         12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
                                         22, 23, 24, 25]},
             scoring='accuracy', verbose=1)

In [18]:
best_parameters = mode.best_params_
print(best_parameters)

{'n_neighbors': 1}

The best value of k is 1 for this case

### Regression using KNN

In [19]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import metrics

Load the Data

In [20]:
boston = datasets.load_boston()

Get Feature (X) and Target (y)

In [21]:
X=boston.data
y=boston.target

Split the dataset into training and testing set

In [22]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

Build the Model

In [23]:
reg=KNeighborsRegressor(n_neighbors=2)

Train the Model

In [24]:
reg.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=2)

 Make the Prediction

In [25]:
y_pred=reg.predict(X_test)

Evaluate the Model

In [26]:
# Different Metrics to Measure the Performance of the Model
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print('R^2 (Coefficient of determination):', metrics.r2_score(y_test,y_pred))

Mean Squared Error: 42.038519736842105
Root Mean Squared Error: 6.483711879536451
R^2 (Coefficient of determination): 0.49512680634286044

Find the Best value of K for the Model

In [27]:
from sklearn.model_selection import GridSearchCV
K_values=[i for i in range(26)]
parameters = {"n_neighbors":K_values}
mode=GridSearchCV(reg, parameters,scoring='r2',verbose=1,refit=True,cv=5,n_jobs=-1)

In [28]:
mode.fit(X_train,y_train)

Fitting 5 folds for each of 26 candidates, totalling 130 fits

GridSearchCV(cv=5, estimator=KNeighborsRegressor(n_neighbors=2), n_jobs=-1,
             param_grid={'n_neighbors': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
                                         12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
                                         22, 23, 24, 25]},
             scoring='r2', verbose=1)

In [29]:
best_parameters = mode.best_params_
print(best_parameters)

{'n_neighbors': 4}

For the regression model we build the best value of k is 4

## Conclusion

In this tutorial we learned how the KNN algorithm works. We implemented the KNN algorithm to build a classifier and regressor using Scikit Learn.