In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Loading the Dataset

In [2]:
df = pd.read_csv("datasets/lifesat.csv")

In [3]:
df.head()

   Country  GDP per capita (USD)  Life satisfaction
0   Russia          26456.387938                5.8
1   Greece          27287.083401                5.4
2   Turkey          28384.987785                5.5
3   Latvia          29932.493910                5.9
4  Hungary          31007.768407                5.6

Removing the Column `Country`

In [4]:
df = df.drop(columns=['Country'])

In [5]:
df.head()

   GDP per capita (USD)  Life satisfaction
0          26456.387938                5.8
1          27287.083401                5.4
2          28384.987785                5.5
3          29932.493910                5.9
4          31007.768407                5.6

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 2 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   GDP per capita (USD)  27 non-null     float64
 1   Life satisfaction     27 non-null     float64
dtypes: float64(2)
memory usage: 564.0 bytes

In [7]:
df.columns = ['per_capita_income','life_sat']

In [8]:
df.head()

   per_capita_income  life_sat
0       26456.387938       5.8
1       27287.083401       5.4
2       28384.987785       5.5
3       29932.493910       5.9
4       31007.768407       5.6

In [10]:
mean_x = df['per_capita_income'].mean()

In [11]:
mean_x

np.float64(41564.521771015454)

In [12]:
mean_y = df['life_sat'].mean()

In [13]:
mean_y

np.float64(6.566666666666666)

In [14]:
df['x_diff_mean'] = df['per_capita_income']-mean_x

In [15]:
df['y_diff_mean'] = df['life_sat']-mean_y

In [16]:
df['x_diff_mean_2'] = df['x_diff_mean']**2

In [17]:
df.head()

   per_capita_income  life_sat   x_diff_mean  y_diff_mean  x_diff_mean_2
0       26456.387938       5.8 -15108.133833    -0.766667   2.282557e+08
1       27287.083401       5.4 -14277.438370    -1.166667   2.038452e+08
2       28384.987785       5.5 -13179.533986    -1.066667   1.737001e+08
3       29932.493910       5.9 -11632.027861    -0.666667   1.353041e+08
4       31007.768407       5.6 -10556.753364    -0.966667   1.114450e+08

In [21]:
beta_1 = sum(df['x_diff_mean']*df['y_diff_mean'])/sum(df['x_diff_mean_2'])

In [22]:
beta_0 = mean_y - (beta_1*mean_x)

In [23]:
print(f"The Equation of line is y={beta_0}+{beta_1}x")

The Equation of line is y=3.7490494273769097+6.77889969434122e-05x

In [24]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in d:\broadway\datascience_8am\wvenv\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in d:\broadway\datascience_8am\wvenv\lib\site-packages (from scikit-learn) (2.3.3)
Requirement already satisfied: scipy>=1.8.0 in d:\broadway\datascience_8am\wvenv\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in d:\broadway\datascience_8am\wvenv\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in d:\broadway\datascience_8am\wvenv\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
model = LinearRegression()

In [36]:
X = df[['per_capita_income']]
y = df['life_sat']

In [37]:
model.fit(X,y)

LinearRegression()

In [39]:
model.intercept_

np.float64(3.7490494273769093)

In [40]:
model.coef_

array([6.77889969e-05])