In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("datasets/lifesat.csv")

In [4]:
df.head()

   Country  GDP per capita (USD)  Life satisfaction
0   Russia          26456.387938                5.8
1   Greece          27287.083401                5.4
2   Turkey          28384.987785                5.5
3   Latvia          29932.493910                5.9
4  Hungary          31007.768407                5.6

In [5]:
df.columns

Index(['Country', 'GDP per capita (USD)', 'Life satisfaction'], dtype='object')

In [6]:
df = df.drop(columns=['Country'])

In [7]:
df.head()

   GDP per capita (USD)  Life satisfaction
0          26456.387938                5.8
1          27287.083401                5.4
2          28384.987785                5.5
3          29932.493910                5.9
4          31007.768407                5.6

In [8]:
df=df.rename(columns={'GDP per capita (USD)':'x','Life satisfaction':'y'})

In [9]:
df.head()

              x    y
0  26456.387938  5.8
1  27287.083401  5.4
2  28384.987785  5.5
3  29932.493910  5.9
4  31007.768407  5.6

In [11]:
x_mean = df['x'].mean()

In [12]:
x_mean

np.float64(41564.521771015454)

In [13]:
y_mean = df['y'].mean()

In [14]:
y_mean

np.float64(6.566666666666666)

In [15]:
df['x_xmean'] = df['x']-x_mean

In [16]:
df['y_ymean'] = df['y']-y_mean

In [17]:
df['x_mean_sq'] = df['x_xmean']**2

In [18]:
df.head()

              x    y       x_xmean   y_ymean     x_mean_sq
0  26456.387938  5.8 -15108.133833 -0.766667  2.282557e+08
1  27287.083401  5.4 -14277.438370 -1.166667  2.038452e+08
2  28384.987785  5.5 -13179.533986 -1.066667  1.737001e+08
3  29932.493910  5.9 -11632.027861 -0.666667  1.353041e+08
4  31007.768407  5.6 -10556.753364 -0.966667  1.114450e+08

In [19]:
beta_1 = sum(df['x_xmean']*df['y_ymean'])/sum(df['x_mean_sq'])

In [20]:
beta_1

6.77889969434122e-05

In [26]:
beta_0 = y_mean-beta_1*x_mean

In [27]:
beta_0

np.float64(3.7490494273769097)

In [28]:
f'{beta_0}+{beta_1}x'

'3.7490494273769097+6.77889969434122e-05x'

In [25]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in d:\broadway\datascience\venv\lib\site-packages (1.7.1)
Requirement already satisfied: numpy>=1.22.0 in d:\broadway\datascience\venv\lib\site-packages (from scikit-learn) (2.3.1)
Requirement already satisfied: scipy>=1.8.0 in d:\broadway\datascience\venv\lib\site-packages (from scikit-learn) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in d:\broadway\datascience\venv\lib\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in d:\broadway\datascience\venv\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 23.2.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
from sklearn.linear_model import LinearRegression

In [30]:
model = LinearRegression()

In [33]:
X = df[['x']]
y = df['y']

In [35]:
model.fit(X,y)

LinearRegression()

In [36]:
model.coef_

array([6.77889969e-05])

In [37]:
model.intercept_

np.float64(3.7490494273769093)